### ISSUE TITLE
[Question] How to backup?

### ISSUE THREAD

**Issue by MrMMorris** [prometheus/promdash#431]
I have this container:

```yaml
docker:
    name: monitoring-ui
    image: prom/promdash:latest
    env:
      SERVICE_NAME: monitoring
      SERVICE_TAGS: ui
      DATABASE_URL: "sqlite3:/tmp/prom/file.sqlite3"
    volumes:
      - /tmp/prom:/tmp/prom
    ports:
      - "3000:3000"
    publish_all_ports: True
    restart_policy: always
```

How do I back up the db? Can I just copy /tmp/prom/file.sqlite3? is there a rake task?
