### ISSUE TITLE
regex issue with relabeling consul service address

### ISSUE THREAD

**Issue by cmesquita** [prometheus/promdash#483]
Hi All -

I use CONSUL as a discovery service mechanism, If a check  the following service in the CONSUL catalog it returns:

```
 curl 172.31.1.3:8500/v1/catalog/service/mysql-lab-9104

{"Node":"172.31.1.3","Address":"172.17.0.2","ServiceID":"721df821bb5e:jovial_banach:9104","ServiceName":"mysql-lab-9104","ServiceTags":null,"ServiceAddress":"172.31.1.1","ServicePort":9104}
```
Prometheus should collect metric from SERVICEADDRESS:SERVICEPORT however Prometheus try to get metrics from Address:ServicePort

I tried to relabel the address with the following replacement, Unfortunatly this configurations didn´t execute with success ::

```yaml
  - job_name: 'overwritten-default'
    consul_sd_configs:
    - server:   '172.31.1.3:8500'
      services: ['mysql-lab-9104']
    relabel_configs:
    - source_labels: ['__meta_consul_service_address']
      regex: '((?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d)\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]\d|\d))'
      replacement: '${1}'
      target_label:  '__meta_consul_address'
```

 Anyone has an idea how to deal with this issue?

best regards,

Cesar

**Comment by juliusv** [comment]
I allowed myself to edit your issue to format the YAML correctly.

I think the following relabeling config should work (not tested):

```yaml
relabel_configs:
- source_labels: ["__meta_consul_service_address", "__meta_consul_service_port"]
  regex: (.+);(\d+)
  replacement: $1:$2
  target_label: __address__
```
